version: '3.3'

services:

  subtitle_editor:
    container_name: subtitle_editor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:5173'
